### ISSUE TITLE
Add dark mode CSS for PrismJs > clipboard.js copy button to fix white text on white button readability problem

### ISSUE THREAD

**Issue by oberocks** [obewds/vueventus#502]
```css
.dark div.code-toolbar > .toolbar > .toolbar-item > button.copy-to-clipboard-button {
    color: black;
}
```
